-- 코드를 작성해주세요
SELECT CONCAT(QUARTER, 'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM (
    SELECT (MONTH(DIFFERENTIATION_DATE)-1) DIV 3 + 1 AS QUARTER
    FROM ECOLI_DATA
) AS SUB
GROUP BY QUARTER
ORDER BY QUARTER;